### ISSUE TITLE
Convert Troubleshooting Basics Lesson Plan

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/troubleshooting-basics#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [ ]  clean up the Markdown
- [ ]  download the old images
- [ ]  upload the images into GitHub
- [ ]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/user-lessons/troubleshooting-basics/

**Comment by man4toman** [comment]
[Update] Convert Lesson Plan to GitHub

- [x] copy and paste from Make site
- [x] clean up the Markdown
- [x] download the old images
- [x] upload the images into GitHub
- [x] swap out the image links

Related PR: #4
